language: clojure
script:
  - lein build
jdk:
  - oraclejdk11
  - oraclejdk8
  - openjdk11
  - openjdk8
env:
  - LEIN_SNAPSHOTS_IN_RELEASE=true
notifications:
  email:
    - duncan.mcgreggor@nasa.gov

